server:
  port: ${IEXEC_RESULT_PROXY_PORT:13200}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:13202}
      auto-index-creation: true # Auto-index creation is disabled by default starting with Spring Data MongoDB 3.x.

chain:
  id: ${IEXEC_CHAIN_ID:134}
  sidechain: ${IEXEC_IS_SIDECHAIN:true}
  node-address: ${IEXEC_BLOCKCHAIN_NODE_ADDRESS:https://bellecour.iex.ec}
  hub-address: ${IEXEC_HUB_ADDRESS:0x3eca1B216A7DF1C7689aEb259fFB83ADFB894E7f}
  block-time: ${IEXEC_BLOCK_TIME:PT5S}
  gas-price-multiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be sent with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gas-price-cap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap

ipfs:
  url: ${IEXEC_IPFS_URL:http://127.0.0.1:5001}

jwt:
  key-path: /data/jwt-sign.key

springdoc:
  packages-to-scan: com.iexec.resultproxy
  paths-to-match: /**
