
server:
  port: ${IEXEC_RESULT_PROXY_PORT:18092}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

chain:
    id: ${IEXEC_CHAIN_ID:17}
    sidechain: ${IEXEC_IS_SIDECHAIN:false}
    privateAddress: ${IEXEC_PRIVATE_CHAIN_ADDRESS:http://localhost:8545}
    publicAddress: ${IEXEC_PUBLIC_CHAIN_ADDRESS:http://localhost:8545}
    hubAddress: ${IEXEC_HUB_ADDRESS:0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC}
    poolAddress: ${POOL_ADDRESS:0xc0c288EC5242E7f53F6594DC7BADF417b69631Ba}
    startBlockNumber: ${IEXEC_START_BLOCK_NUMBER:0}
    gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
    gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap

ipfs:
  host: ${IEXEC_IPFS_HOST:127.0.0.1}
  port: ${IEXEC_IPFS_PORT:5001}
