version: 7.0.2

server:
  port: ${IEXEC_RESULT_PROXY_PORT:13200}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:13202}

chain:
    id: ${IEXEC_CHAIN_ID:17}
    sidechain: ${IEXEC_IS_SIDECHAIN:false}
    privateAddress: ${IEXEC_PRIVATE_CHAIN_ADDRESS:http://localhost:8545}
    publicAddress: ${IEXEC_PUBLIC_CHAIN_ADDRESS:http://localhost:8545}
    hubAddress: ${IEXEC_HUB_ADDRESS:0xBF6B2B07e47326B7c8bfCb4A5460bef9f0Fd2002}
    startBlockNumber: ${IEXEC_START_BLOCK_NUMBER:0}
    gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
    gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap

ipfs:
  host: ${IEXEC_IPFS_HOST:127.0.0.1}
  port: ${IEXEC_IPFS_PORT:5001}
